# Generated by Django 2.1.1 on 2018-10-18 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 18, 1, 44, 225875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 18, 1, 44, 226872, tzinfo=utc)),
        ),
    ]
