# Generated by Django 2.1.1 on 2018-10-18 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20181018_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 18, 2, 18, 214934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 18, 2, 18, 214934, tzinfo=utc)),
        ),
    ]
